ALTER TABLE public.projects
  ADD COLUMN IF NOT EXISTS tagline text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS client text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS overview text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS stats jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS tags jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS bg_class text NOT NULL DEFAULT 'bg-1',
  ADD COLUMN IF NOT EXISTS mock_type text NOT NULL DEFAULT 'light',
  ADD COLUMN IF NOT EXISTS hero_background text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS label text NOT NULL DEFAULT '';